version: '3.9'
services:
  db:
    image: postgres:14.4-alpine
    restart: always
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=my-secret-pw@
      - POSTGRES_DB=trading
    volumes: 
      - ./db-data:/var/lib/postgresql/data
    # networks:
    #   - trading-network

  trading_api:
    image: trading-api
    platform: linux/arm64
    container_name: trading-api
    restart: always
    command: sh -c "yarn generate && node ./src/index.js"
    ports:
      - '8080:8080'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_TAG=trading-api
        - ENVIRONMENT=local
    depends_on:
      - db
    # networks:
    #   - trading-network

# networks:
#   trading-network:
#     driver: bridge