version: '3.9'
services:
  integration_test_db:
    image: postgres:15.2-alpine
    restart: always
    container_name: integration_test_db
    ports:
      - '5431:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=my-secret-pw@
      - POSTGRES_DB=trading_test
